markdown: kramdown
permalink: /:year/:month/:title/
url: http://xrong.org
author: Xuejian Rong
pygments: true

kramdown:
  input: GFM
  syntax_highlighter: rouge


analytics :
  provider : google
  google :
      tracking_id : 'UA-47201105-1'